./uriscv_core/uriscv_defs.sv
./uriscv_core/uriscv_alu.sv
./uriscv_core/uriscv_lsu.sv
./uriscv_core/uriscv_csr.sv
./uriscv_core/uriscv_muldiv.sv
./uriscv_core/uriscv_branch.sv
./uriscv_core/uriscv_core.sv
./uriscv_core/uriscv_tcm.sv
./uriscv_core/uriscv_top.sv
./uriscv_core/uriscv_ahb_top.sv
